#!/bin/bash
IFS=""
dirDestinationBackup=""
year=$(date +%Y)
monthNow=$(date +"%m")
typeBackup=$1
directoryScript=$2
directoryExclude=$3
directoryDestinationBackup=$4

if [ "$typeBackup" = "local" ]; then
	shift
	shift
	shift
	shift
	array=( "$@" )
	for registers in ${array[*]}; do
		name=$(echo $registers | awk -F"," '{print $1}' )
		directoryToBackup=$(echo $registers | awk -F"," '{print $2}' )
		script=$(echo $registers | awk -F"," '{print $3}' )
		maxSizeFiles=$(echo $registers | awk -F"," '{print $4}' )
	 	excludeBackup=$(echo $registers | awk -F"," '{print $5}' )
	 	echo ""
	 	echo "START_FILE "$name
	 	if [ "$excludeBackup" != "" ];then
			module/file check $directoryExclude$excludeBackup
			if [ $? -ne 1 ];then
				excludeBackup="--exclude-from="$directoryExclude$excludeBackup
			fi
	    fi

		if [ "$maxSizeFiles" != "" ]; then
			maxSizeFiles="--max-size="$maxSizeFiles
		fi

		if [ "$script" != "" ]; then
			module/script check $directoryScript$script
			if [ $? -ne 1 ];then
				echo "->execute script "$script
				start=$(date +'%s')
				module/script run $directoryScript$script
				time_elapsed=$(($(date +'%s') - $start))
				echo "->"$time_elapsed" second"
			fi
		fi
		
		dirDestinationBackupAll=$directoryDestinationBackup$year"/"$monthNow
		module/directory check $dirDestinationBackupAll
		if [ $? -eq 1 ];then
			mkdir -p $dirDestinationBackupAll
		fi
		module/directory check $dirDestinationBackupAll
		if [ $? -eq 1 ];then
			break;
		fi
		module/directory check $dirDestinationBackupAll$directoryToBackup
		if [ $? -eq 1 ];then
			mkdir -p $dirDestinationBackupAll$directoryToBackup
		fi
		module/directory check $dirDestinationBackupAll$directoryToBackup
		if [ $? -eq 1 ];then
			break;
		fi


		echo "END_FILE "$name
		echo ""
	done
fi