#!/bin/bash
root=$(pwd);
source $root"/"sys_function.conf

if [ "$1" = "check" ]; then
	function_validate_file $2;
	if [ $? -ne 1 ]; then
		echo "->ERRO_CHECK $2"
		exit 1
	else
		echo "->PASS_CHECK $2"
		exit 0
	fi
fi