#!/bin/bash

dateTime=$(date +%Y/%m/%d" "%H:%M:%S)
content=$2
dirLogs=$3
role=$4
nameLogs=$role"_"$(date +%d%m%Y)".log"
IFS=""
if [ "$1" = "write" ]; then
	echo $dateTime" [$content]" >> $dirLogs$nameLogs
	echo $content
	exit 0
fi

if [ "$1" = "getname" ]; then
	echo $dirLogs$nameLogs;
	exit 0
fi