#!/bin/bash

typeBackup=$1
maxSizeFiles=$2
directoryBackup=$3
dirDestinationBackup=$4
excludeBackup=$5
destComparitionBackup=$6

if [ "$typeBackup" = "total" ]; then
	start=$(date +'%s')
	rsync -av --progress --stats --force --delete-before --max-size=$maxSizeFiles $directoryBackup $dirDestinationBackup$directoryBackup --exclude-from=$excludeBackup
	time_elapsed=$(($(date +'%s') - $start))
	echo "->"$time_elapsed" second"
fi

if [ "$typeBackup" = "incremental" ]; then
	
	rsync -av --progress --stats --force --delete-before --max-size=$maxSizeFiles --prune-empty-dirs $directoryBackup $dirDestinationBackup$directoryBackup --exclude-from=$excludeBackup --compare-dest=$destComparitionBackup$directoryBackup
fi