#!/bin/bash
root=$(pwd);
role=$1
if [ "$role" = "" ]; then echo "->Sin rol definido como parametro"; exit 1; fi
export $(sed -n '1,/'$role'/d;/\[/,$d;/^$/d;p' $root"/"sys_options.conf)
export $(sed -n '1,/system/d;/\[/,$d;/^$/d;p' $root"/"sys_options.conf)
#source $root"/"sys_function.conf
source $root"/"file_manager_test.conf

$root"/"module/directory check $dirInstall
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirExclude
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirScript
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirRootBackup
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirBackupCompressed
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirBackupCompressedUpload
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirCompressedFinal
if [ $? -eq 1 ]; then 	exit 1; fi
$root"/"module/directory check $dirCompressedFinalUpload
if [ $? -eq 1 ]; then 	exit 1; fi

$root"/"module/backup local $dirScript $dirExclude $dirRootBackup  "${backup_list[@]}" 